API_BASE_URL=http://localhost:8082/api/
OAUTH_CALLBACK_SCHEME=https
OAUTH_CALLBACK_HOST=example.com
OAUTH_CALLBACK_PORT=
OAUTH_CALLBACK_PATH=/postlogin
DEBUG_OAUTH_CALLBACK_SCHEME=http
DEBUG_OAUTH_CALLBACK_HOST=localhost
DEBUG_OAUTH_CALLBACK_PORT=8082
DEBUG_OAUTH_CALLBACK_PATH=/postlogin
