name: CI

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.MD'
    branches:
      - "master"
      - "develop"
      - "ft**"
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches:
      - "master"
      - "develop"
  # To run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4.6.0
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Prepare fake google-services.json
        run: cp google-services.json_template app/google-services.json
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build